import 'package:pr3/models/flavor.dart';

final List<Flavor> flavors = [
  Flavor(
    0,
    "Радужный щербет",
    "https://www.baskinrobbins.com.my/sites/default/files/2023-11/Rainbow-Sherbet.jpg",
    "Щербеты со вкусом апельсина, ананаса и малины",
    "без сои, без орехов, без глютена",
    200,
  ),
  Flavor(
    1,
    "Ананас-папайя",
    "https://www.baskinrobbins.com.my/sites/default/files/2023-11/Pineapple-Papaya-Scoop1.jpg",
    "Мороженое со вкусом папайи и ананаса с сочными кусочками ананаса.",
    "без сои, без орехов, без глютена",
    400,
  ),
  Flavor(
    2,
    "Шоколадное с печеньем",
    "https://www.baskinrobbins.com.my/sites/default/files/2023-12/ChocolateCookieCrackle--%28oreo%29.jpg",
    "Классическое шоколадное мороженое с кусочками шоколадного печенья и хрустящей лентой из сливочной помадки",
    "без орехов, без яиц",
    100,
  ),
  Flavor(
    3,
    "Зеленый чай",
    "https://www.baskinrobbins.com.my/sites/default/files/2023-11/Green-Tea.jpg",
    "Мороженое, приготовленное из листьев зеленого чая.",
    "без сои, без орехов, без глютена",
    300,
  ),
  Flavor(
    4,
    "Клубничный чизкейк",
    "https://www.baskinrobbins.com.my/sites/default/files/2023-11/Strawberry-Cheesecake.jpg",
    "Нежное мороженое со вкусом чизкейка с кусочками чизкейка и клубничной лентой",
    "без орехов",
    100,
  ),
  Flavor(
    5,
    "Клубника-питайя",
    "https://www.baskinrobbins.com.my/sites/default/files/2024-01/Website%20-%20Ice%20cream%20Tile%20%281%29.png",
    "Клубнично-фруктовое мороженое с завитком из клубничного драгонфрута.",
    "без сои, без орехов, без глютена, без яиц",
    200,
  ),
  Flavor(
    6,
    "Шоколадный торт с ежевикой и лесными орехами",
    "https://www.baskinrobbins.com.my/sites/default/files/2024-01/Website%20-%20Ice%20cream%20Tile%20%286%29.png",
    "Ежевичное мороженое в сочетании с шоколадным мороженым со вкусом лесного ореха и кусочками печенья со вкусом лесного ореха.",
    "без яиц",
    400,
  ),
  Flavor(
    7,
    "День на пляже",
    "https://www.baskinrobbins.com.my/sites/default/files/2023-11/Beach-Day.jpg",
    "Мороженое с ванилью и голубой морской солью, украшенное черепашками в молочном шоколаде с карамельной начинкой и украшенное лентой из соленого крекера Грэм.",
    "без орехов, без яиц",
    100,
  ),
  Flavor(
    8,
    "Двойной манго",
    "https://www.baskinrobbins.com.my/sites/default/files/2023-11/It-Takes-Two-to-Mango.jpg",
    "Манговое мороженое с кусочками настоящего манго, с манговым сорбетом и украшенное сладкой манговой лентой",
    "без сои, без орехов, без глютена, без яиц",
    100,
  ),
  Flavor(
    9,
    "Сахарная вата",
    "https://www.baskinrobbins.com.my/sites/default/files/2023-11/Cotton-Candy.jpg",
    "Мороженое со вкусом розовой и фиолетовой сахарной ваты.",
    "без молочных продуктов, без орехов, без глютена, без яиц",
    100,
  ),
];
